export type categories =
  | "Taxes:FICA (social security & medicare)"
  | "Taxes:Federal"
  | "Taxes:State & local"
  | "Housing:rent"
  | "Housing:mortgage"
  | "Housing:property taxes"
  | "Housing:gas/electric/oil"
  | "Housing:water/garbage"
  | "Housing:phones"
  | "Housing:tv"
  | "Housing:internet"
  | "Housing:furniture/appliances"
  | "Housing:housekeeper"
  | "Housing:maintenance/repairs"
  | "Food:groceries"
  | "Food:restaurants"
  | "Transportation:gasoline"
  | "Transportation:maintenance/repairs"
  | "Transportation:state registration fees"
  | "Transportation:tolls/parking"
  | "Transportation:public transportation/taxis"
  | "Debt repayments:credit cards/charge cards"
  | "Debt repayments:auto loans"
  | "Debt repayments:student loans"
  | "Debt repayments:other"
  | "Attire:clothing"
  | "Attire:shoes"
  | "Attire:jewelry"
  | "Attire:dry cleaning"
  | "Fun stuff:Entertainment (movies, concerts)"
  | "Fun stuff:Vacation & travel"
  | "Fun stuff:Gifts"
  | "Fun stuff:Hobbies"
  | "Fun stuff:Subscription/memberships"
  | "Fun stuff:Pets"
  | "Fun stuff:Other"
  | "Personal care:Haircuts"
  | "Personal care:makeup"
  | "Personal care:other"
  | "Personal business:Accountant/attorney/financial advisor"
  | "Personal business:other"
  | "Health Care:physicians and hospitals"
  | "Health Care:drugs"
  | "Health Care:dental and visions"
  | "Health Care:therapy"
  | "Health Care:Health club or gym"
  | "Insurance:Homeowners/renter’s"
  | "Insurance:auto"
  | "Insurance:health"
  | "Insurance:life"
  | "Insurance:disability"
  | "Insurance:Long-term care"
  | "Insurance:umbrella liability"
  | "Education:Tuition"
  | "Education:books"
  | "Education:supplies"
  | "Education:room&board"
  | "Children:day care"
  | "Children:toys"
  | "Children:activities"
  | "Children:child support"
  | "Children:charitable donations"
  | "Uncategorized : (";

export type transaction = {
  key: string; //id
  description: string;
  category: categories;
  pricing: number;
  date: string;
};
